### PR TITLE
bumped to 1.20.1

### PR DESCRIPTION
**Pull request by Terebo**
bumped to 1.20.1 (fabric).
It might be unstable as all i did was change the numbers to work for 1.20.1. I haven't noticed anything unusual in the limited time i've tried it, so it should be good enough

### CODE REVIEW

**Comment by tallypaws** [comment]
i might just switch to fabric just for this

**Comment by tallypaws** [comment]
but if you can please do forge

**Comment by Mr-Jokes-3** [comment]
Is there A way to download this?, idk anything much about how github works

**Comment by samuelh2005** [comment]
> Is there A way to download this?, idk anything much about how github works

@Mr-Jokes-3 
You have to download the code and compile it your self. for now ...

**Comment by samuelh2005** [comment]
@Terebo

Since ["multiloader" support](https://github.com/jenchanws/create-track-map/tree/1.19-multiloader-wip) is being developed couldn't you use Architectury so the mod will work on both forge and fabric without having two separate branches.

**Comment by enbyv** [comment]
Will need to check on the stability of this with @jenchanws before merging, and it would need to be merged into its own 1.20 branch.

**Comment by creeper6530** [comment]
> > Is there A way to download this?, idk anything much about how github works
> 
> @Mr-Jokes-3 You have to download the code and compile it your self. for now ...

How do I compile it? I don't see any `Makefile` nor any instructions. (Sorry if it is obvious, I don't develop in Java)

**Comment by samuelh2005** [comment]
> > > Is there A way to download this?, idk anything much about how github works
> > 
> > 
> > @Mr-Jokes-3 You have to download the code and compile it your self. for now ...
> 
> How do I compile it? I don't see any `Makefile` nor any instructions. (Sorry if it is obvious, I don't develop in Java)

@Mr-Jokes-3 You need to make sure you have Java installed (which I guess you do) and run `./gradlew jar` if that doesn't work run `./gradlew build`. A directory called `libs` inside a 'build' one would be produced, inside that `libs` one the actual jar would exist. If you get a permission denied error when running `./graldew` you may need to `chmod +x ./gradlew`.

**Comment by adaliszk** [comment]
A makefile would not hurt if you want to collaborate ;)

**Comment by creeper6530** [comment]
Sorry, but I don't know how to create a makefile for Java programs.

Anyways, I just built and tested this. and nothing seems broken.
The test suite was very basic, consisting of only these mods:
- Minecraft version 1.20.1
- Fabric loader version 0.14.22
- Fabric API version 0.90.0+1.20.1
- Create Fabric version 0.5.1-d-build.1161+mc1.20.1
- Create Track Map built from the forked repo by running `gradlew.bat build`, version non-slim
- Fabric Language Kotlin version 1.10.10+kotlin.1.9.10

I tested all features of the map (tracks, trains, stations, signals, track occupancy, portals). The logs didn't show any deviation from norm and overall there aren't any visual glitches or significant delay either. Simply works as intended out of the box.

In my opinion, after a more in-depth testing that I don't have time nor knowledge to do, it should be ready for release.

**Comment by samuelh2005** [comment]
@creeper6530 Nice! Also, creating a Makefile for Java is just like creating a Makefile for c / c+.

This one might work. Just place a new Makefile into the directory where you cloned the code into.

```Makefile
build:
    ./gradlew build
jar:
    ./gradlew jar
```

**Comment by creeper6530** [comment]
After forking the main repo and merging Terebo's changes into it, building the mod and plugging it into a copy of decent-sized modpack (32 mods, ranging from large to small additions), I had it run on my single-player world no problem. I feel confident saying that it is just as stable as 1.19 version.

Even though I'm not 100% sure, it will probably be stable on dedicated server too. It would be really great from @jenchanws to finally review this PR and merge it.

<details>
<summary>Full mod list used (all up-to-date on Fabric Stable for 1.20.1):</summary>

[FPS Monitor](https://modrinth.com/mod/fps-monitor)
[Wildfire's Female Gender Mod](https://modrinth.com/mod/female-gender)
[No Chat Reports](https://modrinth.com/mod/no-chat-reports)
[Create: Steam 'n' Rails](https://modrinth.com/mod/create-steam-n-rails)
[Xaero's World Map](https://modrinth.com/mod/xaeros-world-map)
[Xaero's Minimap](https://modrinth.com/mod/xaeros-minimap)
[AppleSkin](https://modrinth.com/mod/appleskin)
[bad packets](https://modrinth.com/mod/badpackets)
[Chat Heads](https://modrinth.com/mod/chat-heads)
[Chunk Loaders](https://modrinth.com/mod/chunk-loaders)
[Cloth Config API](https://modrinth.com/mod/cloth-config)
[Create Fabric](https://modrinth.com/mod/create-fabric)
Create Track Map (self-built)
[Create Crafts & Additions](https://modrinth.com/mod/createaddition)
[Create: Diesel Generators [Fabric]](https://modrinth.com/mod/create-diesel-generators-fabric)
[Dark Loading Screen](https://modrinth.com/mod/dark-loading-screen)
[Dynamic FPS](https://modrinth.com/mod/dynamic-fps)
[Entity Culling](https://modrinth.com/mod/entityculling)
[Fabric API](https://modrinth.com/mod/fabric-api)
[Fabric Language Kotlin](https://modrinth.com/mod/fabric-language-kotlin)
[FerriteCore](https://modrinth.com/mod/ferrite-core)
[Just Enough Items](https://modrinth.com/mod/jei)
[LambDynamicLights](https://modrinth.com/mod/lambdynamiclights)
[LazyDFU](https://modrinth.com/mod/lazydfu)
[Lithium](https://modrinth.com/mod/lithium)
[Memory Leak Fix](https://modrinth.com/mod/memoryleakfix)
[Mod Menu](https://modrinth.com/mod/modmenu)
[Sound Physics Remastered](https://modrinth.com/mod/sound-physics-remastered)
[SuperMartijn642's Config Lib](https://modrinth.com/mod/supermartijn642s-config-lib)
[SuperMartijn642's Core Lib](https://modrinth.com/mod/supermartijn642s-core-lib)
[Simple Voice Chat](https://modrinth.com/mod/simple-voice-chat)
[WTHIT](https://modrinth.com/mod/wthit)

</details>

**Comment by enbyv** [comment]
Thank you @Terebo for this - @jenchanws has now updated this on a new branch so I'll close this PR

**Pull request closed without merging**
